### findAll
GET http://localhost:8080/api-sicpre/products/all HTTP/1.1

### findEnable
GET http://localhost:8080/api-sicpre/products/all/enable HTTP/1.1

### findById
GET http://localhost:8080/api-sicpre/products/2 HTTP/1.1

### save
POST http://localhost:8080/api-sicpre/products/save HTTP/1.1
Content-Type: application/json

{
    "fit_pdt": "NIÑA",
    "num_pdt": 2,
    "skuPrenda_pdt": "n2",
    "nombre_pdt": "Playera polo manga corta",
    "matKin_pdt": "MATERNAL Y KINDER",
    "talla_pdt": "S-M-L",
    "consumo_pdt": 0.45,
    "tipTela_pdt": "Piqué Peso Medio 50/50 Bco",
    "costoMT_pdt": 70,
    "costoTela_pdt": 31.5,
    "costoEtiqueta_pdt": 2,
    "costoBoton_pdt": 3,
    "costoMaquila_pdt": 30,
    "costoAcabado_pdt": 5,
    "costoBordSeri_pdt": 10,
    "costoEmpaque_pdt": 12,
    "costoTrans_pdt": 8,
    "costoAdmin_pdt": 15,
    "costoOtro_pdt": 10,
    "comisVenta_pdt": 15,
    "image_pdt": "Playera",
    "provider_pdt": 1
}

### update
PUT http://localhost:8080/api-sicpre/products/update HTTP/1.1
Content-Type: application/json

{
    "id_pdt": 2,
    "fit_pdt": "NIÑA",
    "num_pdt": 2,
    "skuPrenda_pdt": "n2",
    "nombre_pdt": "Playera polo manga corta",
    "matKin_pdt": "MATERNAL Y KINDER",
    "talla_pdt": "S-M-L",
    "consumo_pdt": 0.45,
    "tipTela_pdt": "Piqué Peso Medio 50/50 Bco",
    "costoMT_pdt": 70,
    "costoTela_pdt": 31.5,
    "costoEtiqueta_pdt": 2,
    "costoBoton_pdt": 3,
    "costoMaquila_pdt": 30,
    "costoAcabado_pdt": 5,
    "costoBordSeri_pdt": 10,
    "costoEmpaque_pdt": 12,
    "costoTrans_pdt": 8,
    "costoAdmin_pdt": 15,
    "costoOtro_pdt": 10,
    "comisVenta_pdt": 15,
    "image_pdt": "Playera",
    "provider_pdt": 1
}

### disable
PUT http://localhost:8080/api-sicpre/products/disable/2 HTTP/1.1

### enable
PUT http://localhost:8080/api-sicpre/products/enable/2 HTTP/1.1
