### findAll
GET http://localhost:8080/api-sicpre/products/all HTTP/1.1

### findEnable
GET http://localhost:8080/api-sicpre/products/all/enable HTTP/1.1

### findById
GET http://localhost:8080/api-sicpre/products/2 HTTP/1.1

### save
POST http://localhost:8080/api-sicpre/products/save HTTP/1.1
Content-Type: application/json

{
    "fit_pdt": "NIÑO",
    "num_pdt": 6,
    "skuPrenda_pdt": "n6",
    "nombre_pdt": "Suéter escolar unisex",
    "matKin_pdt": "MATERNAL Y KINDER",
    "talla_pdt": "S-M-L",
    "consumo_pdt": 0,
    "tipTela_pdt": "COMPRADO",
    "costoMT_pdt": 0,
    "costoTela_pdt": 0,
    "costoEtiqueta_pdt": 0,
    "costoBoton_pdt": 0,
    "costoMaquila_pdt": 0,
    "costoAcabado_pdt": 0,
    "costoBordSeri_pdt": 0,
    "costoEmpaque_pdt": 0,
    "costoTrans_pdt": 0,
    "costoAdmin_pdt": 0,
    "costoOtro_pdt": 0,
    "comisVenta_pdt": 0,
    "image_pdt": null,
    "provider_pdt": 1
}

### update
PUT http://localhost:8080/api-sicpre/products/update HTTP/1.1
Content-Type: application/json

{
    "id_pdt": 6,
    "fit_pdt": "NIÑ0",
    "num_pdt": 4,
    "skuPrenda_pdt": "n4",
    "nombre_pdt": "Suéter escolar  (nuevo diseño) unisex",
    "matKin_pdt": "MATERNAL Y KINDER",
    "talla_pdt": "S-M-L",
    "consumo_pdt": 0,
    "tipTela_pdt": "COMPRADO",
    "costoMT_pdt": 120,
    "costoTela_pdt": 120,
    "costoEtiqueta_pdt": 2,
    "costoBoton_pdt": 9,
    "costoMaquila_pdt": 0,
    "costoAcabado_pdt": 0,
    "costoBordSeri_pdt": 15,
    "costoEmpaque_pdt": 12,
    "costoTrans_pdt": 8,
    "costoAdmin_pdt": 15,
    "costoOtro_pdt": 10,
    "comisVenta_pdt": 15,
    "image_pdt": "Sueter",
    "provider_pdt": 1
}

### disable
PUT http://localhost:8080/api-sicpre/products/disable/3 HTTP/1.1

### enable
PUT http://localhost:8080/api-sicpre/products/enable/3 HTTP/1.1
