### findAll
GET http://localhost:8080/api-sicpre/providers/all HTTP/1.1

### findEnable
GET http://localhost:8080/api-sicpre/providers/all/enable HTTP/1.1

### findById
GET http://localhost:8080/api-sicpre/providers/2 HTTP/1.1

### save
POST http://localhost:8080/api-sicpre/providers/save HTTP/1.1
Content-Type: application/json

{
    "rfc_pvd": "PID170429GJ1",
    "name_pvd": "Centro de Innovacion y Diseño(DIC)",
    "dirFis_pvd": "11 Sur 2104, Primer Piso, Colonia Centro, Puebla, EUA",
    "dirSuc_pvd": "11 Sur 2104, Primer Piso, Colonia Centro, Puebla, EUA",
    "phone_pvd": "222 918 92 57",
    "email_pvd": "asistenciapuebla@cidpuebla.com"
}

### update
PUT http://localhost:8080/api-sicpre/providers/update HTTP/1.1
Content-Type: application/json

{
    "id_pvd": 2,
    "rfc_pvd": "PID170429GJ1",
    "name_pvd": "Centro de Innovacion y Diseño(DIC)",
    "dirFis_pvd": "11 Sur 2104, Primer Piso, Colonia Centro, Puebla, EUA",
    "dirSuc_pvd": "11 Sur 2104, Primer Piso, Colonia Centro, Puebla, EUA",
    "phone_pvd": "222 918 92 57",
    "email_pvd": "asistenciapuebla@cidpuebla.com"
}

### disable
PUT http://localhost:8080/api-sicpre/providers/disable/2 HTTP/1.1

### enable
PUT http://localhost:8080/api-sicpre/providers/enable/2 HTTP/1.1