### findAll
GET http://localhost:8080/api-sicpre/users/all HTTP/1.1

### findEnable
GET http://localhost:8080/api-sicpre/users/all/enable HTTP/1.1

### findById
GET http://localhost:8080/api-sicpre/users/2 HTTP/1.1

### save
POST http://localhost:8080/api-sicpre/users/save HTTP/1.1
Content-Type: application/json

{
    "name_usr": "Tomas",
    "lastname_usr": "Peralta",
    "role_usr": "Administrador",
    "email_usr": "tomas@gmail.com",
    "password_usr": "123456"
}

### register
POST http://localhost:8080/api-sicpre/users/register HTTP/1.1
Content-Type: application/json

{
    "name_usr": "Cecilia",
    "lastname_usr": "Valdez",
    "email_usr": "cecilia@gmail.com",
    "password_usr": "123456"
}

### update
PUT http://localhost:8080/api-sicpre/users/update HTTP/1.1
Content-Type: application/json

{
    "usuarioId_usr": 2,
    "name_usr": "Emilio",
    "lastname_usr": "Peralta",
    "role_usr": "Administrador",
    "email_usr": "emilio@gmail.com",
    "password_usr": "123456"
}

### disable
PUT http://localhost:8080/api-sicpre/users/disable/2 HTTP/1.1

### enable
PUT http://localhost:8080/api-sicpre/users/enable/2 HTTP/1.1